### ISSUE TITLE
Is there a way to show subcommand option if using multiple files for each subcommand

### ISSUE THREAD

**Issue by Aziz-repo** [tiangolo/typer#401]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# main file
import typer

import commands

app = typer.Typer()

app.add_typer(typer_instance=commands.make_structure.app, name="create", help="Create the project structure")
app.add_typer(typer_instance=commands.lang_choise.app, name="lang", help="Pick C or Cpp language")

# TODO: add a callback to the CLI indicate what's going on!!!


if __name__== "__main__":
    app()

## make_structure file 
from typing import Optional
import typer
import os
from utils.utils import build_hiarchy

app = typer.Typer()

# TODO: write the docs for every componenent in the app
@app.command("create")
def make_struct(name: str = typer.Option(...,"--name", "-n"), verbose: bool=typer.Option(False, "--verbose", "-v")) -> int:
    dir = os.getcwd()
    subdirs_to_create = ["src", "bin", "obj"]
    file_to_create = "Makefile"
    project_directory = os.path.join(dir,name)
    # build hiarchy
    if build_hiarchy(project_directory, subdirs_to_create, file_to_create, verbose) == 0:
        return 0
    typer.echo("exit code 1")
    return 1



if __name__ == "__main__":
   app()

## lang_choice file

import typer
from utils.utils import create_main
from enums.prog_lang import ProgLang


app = typer.Typer()


@app.command("lang")
def language_choise(lang: ProgLang = ProgLang.c.value):
    # set the directory to work with
    
    if lang.value == "C":
        # TODO: create the main file in /src directory and write to it
        lang_code = 0
        if create_main(lang_code) != 0:
            print("exit code 2")
            return 2
        # TODO: Write in the makefile
        pass
    else:
        # TODO: create the main file in /src directory and write to it
        lang_code = 1
        if (create_main(lang_code) != 0):
            print("exit code 2")
            return 2
        # TODO: write in the makefile
        pass
```

### Description

I started to create a CLI with typer and I'm facing a problem.
I used multiple files in my project where the commands are in a certain file and the main program is located in the main workspace directory
1.main : file
2.command: package
  1. command1 : file
  2. command2 : file

When I run the program and call some of the command with --help option it doesn't show the option available for that command
![help](https://user-images.githubusercontent.com/81187136/172913653-ab1d14bb-66e4-4a1f-8c44-25f4296d77de.jpg)

### Operating System

Linux

### Typer Version

0.3.2

### Python Version

3.9.8
